config/routes.rb
Nomster::Application.routes.draw do
  devise_for :users

  root 'places#index'

  resources :places do
    resources :comments, :only => :create
      member do
        put 'like', to: 'places#upvote'
        put 'dislike', to: 'places#downvote'
      end
  end

  resources :places do
    resources :photos, :only => :create
  end

   
  resources :users, :only => :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

   RATINGS = {
    'one star'    => '1_star',
    'two stars'   => '2_stars',
    'three stars' => '3_stars',
    'four stars'  => '4_stars',
    'five stars'  => '5_stars'
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end

  def number_of_stars
    "*" * self.rating.to_i 
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :place
  # validates :place, presence: true
end

app/models/place.rb
class Place < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :photos, :dependent => :destroy
  
  geocoded_by :address
  after_validation :geocode
  
  validates :name, :address, :description, :presence => true
  validates :name, length: { :minimum => 3, :maximum => 100 }

  def self.search(search)
    where('name LIKE ?', "%#{search}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    puts params
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(:user => current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
  end


  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy, :upvote, :downvote]

  # def index
  #   # @places = Place.all.page(params[:page]).per(3)
  #   @places = Place.search(params[:search])
  # end

  def index
  @places = Place.search(params[:search])
    if @places.class == Array
      @places = Kaminari.paginate_array(@posts).page(params[:page]).per(3) 
    else
      @places = @places.page(params[:page]).per(3) # if @posts is AR::Relation object 
    end
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end  
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end

    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end

    @place.destroy
    redirect_to root_path
  end


  def upvote
    @place = Place.find(params[:id])
    @place.liked_by current_user
    redirect_to :back
  end

  def downvote
    @place = Place.find(params[:id])
    @place.downvote_from current_user
    redirect_to :back
  end


  private

  def place_params
    params.require(:place).permit(:name, :address, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nomster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to 'PIZZA DE CHICAGO', root_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to new_place_path do %>
          <i class="glyphicon glyphicon-plus-sign"></i>
          New Place
          <% end %>

          
  
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to 'My Profile', user_path(current_user) %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div id='alert'>
  <% if notice.present? %>
    <div class='alert alert-warning alert-dismissible' role='alert'>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      <%= notice %>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class='alert alert-warning alert-dismissible' role='alert'>
      <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      <%= alert %>
    </div>
  <% end %>
</div><!-- alert -->


<%= yield %>


</body>
</html>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit Your Place</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', :class => 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
     <%= image_tag 'slider1.jpg', :class => 'img-responsive' %>
      <div class="carousel-caption">
        FIND THE BEST PIZZA IN CHICAGO
      </div>
    </div>
      <div class="item">
    <%= image_tag 'slider2.jpg', :class => 'img-responsive' %>
    <div class="carousel-caption">
      <!-- Looking for hotdogs? -->
    </div>
  </div>
    <div class="item">
    <%= image_tag 'slider3.jpg', :class => 'img-responsive' %>
    <div class="carousel-caption">
      <!-- Hungry? -->
    </div>
  </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<!--map -->
<div class="main">
  <div class="map-sidebar col-xs-12 col-sm-4 pull-right">

    <!--search engine-->
    <%= form_tag places_path, method:'get', :class => 'form-inline' do %>
      <div class = 'form-group'>
        <%= text_field_tag :search, params[:search], placeholder: 'Restaurant Name', :class => 'form-control' %>
        <%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
      </div>
    <% end %>
    <br>

    <h4>Best Pizzas in Chicago</h4>
    <br />
    <div id="map"></div>
    <br />
    <br />
    <h4>About Pizza De Chicago</h4>
    <br />
    <p>We list best pizza places in Chicago.  Please feel free to add your place in town!</p>


  </div>


    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script type="text/javascript">
    // http://stackoverflow.com/questions/3059044/google-maps-js-api-v3-simple-multiple-marker-example
    // http://stackoverflow.com/questions/16825290/google-maps-api-v3-adding-multiple-markers-w-info-windows-w-custom-text
      var locations = [
        <% @places.each do |place| %>
          <% if place == @places.last %>
          ['<%= link_to place.name, place_path(place) %><br/><%= place.description %>', <%= place.latitude %>, <%= place.longitude %>, 4]
          <% else %>
          ['<%= link_to place.name, place_path(place) %><br/><%= place.description %>', <%= place.latitude %>, <%= place.longitude %>, 4],
          <% end %>
        <% end %>
      ];
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 10,   
        center: new google.maps.LatLng(41.8938119, -87.664622),
        mapTypeId: google.maps.MapTypeId.ROADMAP
      });
      var infowindow = new google.maps.InfoWindow();
      var marker, i;
      for (i = 0; i < locations.length; i++) {  
        marker = new google.maps.Marker({
          position: new google.maps.LatLng(locations[i][1], locations[i][2]),
          map: map
        });
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
          return function() {
            infowindow.setContent(locations[i][0]);
            infowindow.open(map, marker);
          }
        })(marker, i));
      }
    </script>

    <!-- restaurant -->



    <% @places.each do |place| %>
      <div class="booyah-box col-xs-12 col-sm-8 left-main">
        <div class="col-sm-8">
          <h1><%= link_to place.name, place_path(place) %></h1>
          <i><%= place.address %></i><br><br>
          <p><%= place.description %></p><br>


          <% if place.user.present? %>
            <small><%= place.user.email %></small>
          <% end %>

          <div class='like-button'>
            <button><%= link_to 'I like it', like_place_path(place), method: :put%>
            <%= place.get_upvotes.size %></button>
        
            <button><%= link_to 'Unlike', dislike_place_path(place), method: :put %>
            <%= place.get_downvotes.size %></button>
          </div>


          <br><br>
        </div>
        
        <div class="photo-in-index-page col-sm-4">
          <% if place.photos.present? %> 
            <%= link_to image_tag(place.photos.first.picture, :class => 'img-thumbnail index-image'), place_path(place)  %>
          <% end %>
        </div>



        <div class="clear"></div>
          <%if place.comments.present? %>
            <div class="col-xs-12">
              <blockquote>
                <% if place.comments.last.humanized_rating.present? %>
                  <b><%= place.comments.last.humanized_rating %></b> -
                <% end %>
                <%= place.comments.last.message %>
                <small><%= place.comments.last.user.email %></small>
              </blockquote>
            </div>
          <% end %>
        </div>
      

        
    <% end %>

  
    <div class="col-xs-12 col-sm-12 text-center">
    <%= paginate @places %>
    </div>
</div><!-- main -->

app/views/places/new.html.erb
<div class="booyah-box col-xs-7 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Create', :class => 'btn btn-primary' %>

  <% end %>

</div>

app/views/places/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <div class="pull-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), :class => 'btn btn-primary' %>
      <%= link_to 'Delete', place_path(@place), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this?'},:class => 'btn btn-danger' %>
    <% end %>
    
  </div>


  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>



<% if @place.latitude.present? && @place.longitude.present? %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <script>
    function initialize() {
      var myLatlng = new google.maps.LatLng(<%= @place.latitude %>,<%= @place.longitude %>);
      var mapOptions = {
        zoom: 12,
        center: myLatlng
      };
      var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

      var marker = new google.maps.Marker({
        position: myLatlng,
        map: map,
        title: 'Hello World!'
      });
    }

    google.maps.event.addDomListener(window, 'load', initialize);

  </script>

  <div id="map-canvas"></div>
<% end %>

<br />
 
<div class="clear"></div>
<div class="photo">
  <% @place.photos.each do |photo| %>
  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3 text-center">
   
    <a class="fancybox" href="<%= photo.picture %>"><%= image_tag photo.picture, :class => 'img-responsive, img-thumbnail' %></a>
    <%= photo.caption %>
  </div>
  <% end %>
</div>

  

  

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for @comment, :url => place_comments_path(@place) do |f| %>
          <%= f.input :message %>
          <%= f.input :rating, :as => :select, :collection => Comment::RATINGS %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Comment", :class => 'btn btn-primary' %>
           </div>
          <% end %>
      </div>
    </div>
  </div>

 <div class="clear"></div>

  <div class="col-xs-12 col-sm-12">
    <br><br>
    <h2 class="col-sm-6 col-md-8">Comments</h2>
      <!-- Button trigger modal -->
      <div class="col-sm-3 col-md-2">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
          Add a comment
        </button>
      </div>

      <div class="col-sm-3 col-md-2">
         <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal2">
          Add a picture
        </button>
      </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a comment</h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for @photo, multiple: true, :url => place_photos_path(@place) do |f| %>
          <%= f.input :caption %>
          <%= f.input :picture %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Picture", :class => 'btn btn-primary' %>
           </div>
          <% end %>
      </div>
    </div>
  </div>

  
  <div class="col-xs-10 col-xs-offset-1">

      <!-- Button trigger modal -->
     

  </div> 
  <div class="clear"></div>

  <% @place.comments.each do |comment| %>
     <div class="col-xs-12 col-sm-6">
      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>
</div>


<script type="text/javascript">
jQuery(function() {
  $("a.fancybox").fancybox();
});
</script>

app/views/users/show.html.erb
<div class="booyah-box">
  <div class="col-xs-12 col-sm-4">
    <%= image_tag 'user.png' %>
  </div>

  <div class="col-xs-12 col-sm-8">
    <h3><%= @user.email %></h3>
    <p>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></p>

    <h4><%= @user.comments.count %> total comments</h4>
    <h4><%= @user.comments.where(:rating => '5_stars').count %> total 5 star reviews</h4>
  </div>
  <div class="clear"></div>
</div>

<br><br>
<h1 class="text-center">My Comments</h1>
<br><br>
<% @user.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-6">
      <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>
    <blockquote>
      <% if comment.humanized_rating.present? %>
        <b><%= comment.humanized_rating %></b> -
      <% end %>
      <%= comment.message %>
      <small><%= comment.user.email %></small>
    </blockquote>
  </div>
<% end %>

<div class="clear"></div>
<br><br>
<h2 class="text-center">My Places</h2>
<br><br>

<% @user.places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>

    <% if place.comments.present? %>
      <div class="col-xs-12">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
<% end %>